server_url: 'http://localhost:8000/'
path_mapping: ''
incrementalbuild_url: ''
build_published: true
preview_entity_types: {  }
preview_callback_url: 'http://localhost:8000/'
_core:
  default_config_hash: '-xBft7gLYifC9YdTJUXA0W_QNDfPVcU6D9NjOFCdjYU'
secret_key: ''
